//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForm_Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class form
    {
        public int id { get; set; }
        public string cr10 { get; set; }
        public string cr11 { get; set; }
        public string cr12 { get; set; }
        public string cr16 { get; set; }
        public string cr21 { get; set; }
        public string cr22 { get; set; }
        public string cr23 { get; set; }
        public string cr17a { get; set; }
        public string cr17b { get; set; }
        public string cr18a { get; set; }
        public string cr18b { get; set; }
        public string cr19a { get; set; }
        public string cr19b { get; set; }
        public string cr20a { get; set; }
        public string cr20b { get; set; }
        public string cr24a { get; set; }
        public string cr24b { get; set; }
        public string cr24c { get; set; }
        public string cr24d { get; set; }
        public string cr24e { get; set; }
        public string cr24f { get; set; }
        public string cr25a { get; set; }
        public string cr25b { get; set; }
        public string cr25c { get; set; }
        public string cr26a { get; set; }
        public string cr26b { get; set; }
        public string cr26c { get; set; }
        public string cr26d { get; set; }
        public string cr27a { get; set; }
        public string cr27b { get; set; }
        public string cr27c { get; set; }
        public string cr28a01 { get; set; }
        public string cr28a02 { get; set; }
        public string cr28b01 { get; set; }
        public string cr28b02 { get; set; }
        public string cr28c01 { get; set; }
        public string cr28c02 { get; set; }
        public string cr28d01 { get; set; }
        public string cr28d02 { get; set; }
        public string cr28e01 { get; set; }
        public string cr28e02 { get; set; }
        public string cr28f01 { get; set; }
        public string cr28f02 { get; set; }
        public string cr28fx01 { get; set; }
        public string cr28fx02 { get; set; }
    }
}
