//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForm_Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class village
    {
        public int id { get; set; }
        public string country { get; set; }
        public string district { get; set; }
        public string uc { get; set; }
        public string village1 { get; set; }
        public string country_code { get; set; }
        public string district_code { get; set; }
        public string uc_code { get; set; }
        public string villlage_code { get; set; }
        public string cluster_no { get; set; }
    }
}
