//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForm_Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class village
    {
        public int id { get; set; }
        public Nullable<decimal> country { get; set; }
        public Nullable<decimal> district { get; set; }
        public Nullable<decimal> uc { get; set; }
        public Nullable<decimal> village1 { get; set; }
        public Nullable<decimal> country_code { get; set; }
        public Nullable<decimal> district_code { get; set; }
        public Nullable<decimal> uc_code { get; set; }
        public Nullable<decimal> villlage_code { get; set; }
        public Nullable<decimal> cluster_no { get; set; }
    }
}
